Repository elementary/files, pull requests merged in 2018-03, with the labels that each got.

#340 Ensure cursor follows helper selection without losing existing selection
  src/View/AbstractDirectoryView.vala
Labels: Bitesize

#348 Install missing service file
  data/CMakeLists.txt
Labels: Bitesize, Priority: High

#367 Install appdata.xml to metainfo
  data/CMakeLists.txt
Labels: Bitesize

#357 Avoid missing thumbnails
  src/Thumbnailer.vala
  src/View/AbstractDirectoryView.vala
Labels: Priority: High
