Repository elementary/files, pull requests merged in 2019-10, with the labels that each got.

#1055 Reduce DiskRenderer contrast when inactive
  data/styles/DiskRenderer.css
Labels: Bitesize

#1069 Check non-null ftype in GOF.File.update_type ()
  libcore/File.vala
Labels: Bitesize

#1016 Git plugin
  meson.build
  plugins/git/meson.build
  plugins/git/pantheon-files-git.plug
  plugins/git/plugin.vala
  plugins/meson.build
  vapi/libgit2-glib-1.0.vapi
Labels: Status: In Progress

#1073 No drag with secondary button on empty space
  src/View/AbstractDirectoryView.vala
Labels: Bitesize, Priority: Critical
