Repository elementary/files, pull requests merged in 2019-01, with the labels that each got.

#838 Show correct default app for e.g. text files
  libcore/gof-file.vapi
Labels: Needs Design

#795 Fix initial search window size too small
  libwidgets/View/SearchResults.vala
Labels: Priority: Medium

#757 Fix inconsistent free space on device in sidebar and properties window
  src/Dialogs/AbstractPropertiesDialog.vala
  src/Dialogs/PropertiesWindow.vala
  src/Dialogs/VolumePropertiesWindow.vala
Labels: Needs Design

#833 Fix color tag display; make ctag plug re-entrant
  libcore/FileUtils.vala
  pantheon-files-daemon/marlind-tagging.vala
  plugins/pantheon-files-ctags/plugin.vala
Labels: Priority: High

#860 Some i18n fixes:
  data/io.elementary.files.desktop.in.in
  libcore/FileUtils.vala
  po/POTFILES
  po/extra/extra.pot
  po/extra/meson.build
  po/io.elementary.files.pot
  po/meson.build
Labels: i18n

#861 Add subdir to pkg.generate so header is found by dependent apps
  libcore/meson.build
  libwidgets/meson.build
Labels: Status: In Progress

#809 Implement a 'Hide Local Thumbnails' option
  data/schemas/io.elementary.files.gschema.xml
  libcore/gof-preferences.vala
  src/Application.vala
  src/View/AbstractDirectoryView.vala
  src/View/Window.vala
  src/View/directory_view_popup.ui
Labels: Priority: Wishlist

#865 File.vala: Fix inverted logic in get_default_handler
  libcore/File.vala
Labels: Bitesize, Priority: High

#869 Lose intltool dependency
  data/io.elementary.files.policy.in.in
  data/meson.build
  po/extra/POTFILES
  po/extra/extra.pot
  po/its/polkit.its
  po/its/polkit.loc
Labels: Status: In Progress

#874 Remove soversion argument for core and widget libraries
  libcore/meson.build
  libwidgets/meson.build
Labels: Bitesize
