Repository elementary/files, pull requests merged in 2019-08, with the labels that each got.

#1001 Draw checkerboard background for image items
  libcore/File.vala
  src/IconRenderer.vala
Labels: Status: In Progress

#1026 Window: Fix first run coords
  src/View/Window.vala
Labels: Bitesize

#754 Fix unequal and incorrect disk usage bars
  src/View/Sidebar.vala
  src/View/Widgets/DiskRenderer.vala
Labels: Needs Design
