Repository elementary/files, pull requests merged in 2020-08, with the labels that each got.

#1403 Sidebar: Show basename for bind mounts as well as mount name to avoid duplicate device entries
  src/View/Sidebar.vala
Labels: Bitesize

#1420 Release 4.5.0
  data/io.elementary.files.appdata.xml.in.in
  meson.build
Labels: Release

#1428 Revert "core: Port some function to Vala (#1369)"
  libcore/FileUtils.vala
  libcore/marlin-file-operations.c
  meson.build
Labels: Priority: Critical

#1439 Control: add handy to build deps
  debian/control
Labels: Bitesize
