Repository elementary/files, pull requests merged in 2021-08, with the labels that each got.

#1776 Release 6.0.1
  data/io.elementary.files.appdata.xml.in.in
  meson.build
Labels: Release

#1809 FileUtils: Remove unnecessary trailing whitespace
  libcore/FileUtils.vala
Labels: Bitesize, i18n

#1773 Hide scrollbar while renaming
  src/View/AbstractDirectoryView.vala
Labels: Bitesize
