Repository elementary/files, pull requests merged in 2021-09, with the labels that each got.

#1831 Fix regression: Ctrl-Click on bookmark to open in new tab.
  data/io.elementary.files.appdata.xml.in.in
  src/View/Sidebar/BookmarkRow.vala
Labels: Bitesize

#1840 Release 6.0.3
  data/io.elementary.files.appdata.xml.in.in
  meson.build
Labels: Release

#1820 Show translated bookmarks when user language changed
  libcore/Bookmark.vala
  libcore/BookmarkList.vala
  libcore/Interfaces/SidebarInterface.vala
  libwidgets/View/SearchResults.vala
  src/View/AbstractDirectoryView.vala
  src/View/Sidebar/BookmarkListBox.vala
  src/View/Sidebar/BookmarkRow.vala
  src/View/Sidebar/SidebarItemInterface.vala
  src/View/Sidebar/SidebarListInterface.vala
  src/View/Sidebar/SidebarWindow.vala
  src/View/Window.vala
Labels: Accessibility
