Repository elementary/files, pull requests merged in 2021-12, with the labels that each got.

#1927 Sync trash icon
  libcore/TrashMonitor.vala
  src/View/Sidebar/BookmarkListBox.vala
Labels: Bitesize, Regression

#1933 Release 6.1.1
  data/io.elementary.files.appdata.xml.in.in
  meson.build
Labels: Release

#1952 AppData: Fix a typo
  data/io.elementary.files.appdata.xml.in.in
Labels: Bitesize

#1963 AppData: Use "grid" instead of "icon" for consistency with UI
  data/io.elementary.files.appdata.xml.in.in
Labels: Bitesize

#1967 Fix double-spaced text
  libcore/marlin-file-operations.c
Labels: Bitesize
