Repository elementary/files, pull requests merged in 2021-11, with the labels that each got.

#1847 Do not lose pathbar entry text if another window is focused
  data/io.elementary.files.appdata.xml.in.in
  libwidgets/Chrome/BasicBreadcrumbsEntry.vala
  src/View/Widgets/LocationBar.vala
Labels: Bitesize

#1912 FileChooserDialog: use Gtk.CheckButton.with_label
  filechooser-portal/FileChooserDialog.vala
Labels: Bitesize

#1897 Release 6.1.0
  data/io.elementary.files.appdata.xml.in.in
  meson.build
Labels: Release

#1916 POTFILES: Add FileChooserDialog.vala
  po/POTFILES
Labels: Bitesize, i18n
