Repository elementary/files, pull requests merged in 2023-09, with the labels that each got.

#2316 [Crash] Add null file check before updating thumbnail and plugins
  src/View/AbstractDirectoryView.vala
Labels: Priority: Critical

#2303 Handle restoring non-existent locations
  src/Application.vala
  src/View/Window.vala
Labels: Priority: High

#2319 Release 6.5.1
  data/files.metainfo.xml.in.in
  meson.build
Labels: Release

#2322 [Crash] Fix opening Files with xdg-open , FileManager1 or shortcut
  src/View/Window.vala
Labels: Priority: Critical

#2323 Release version 6.5.2
  data/files.metainfo.xml.in.in
  meson.build
Labels: Release
