Repository elementary/files, pull requests merged in 2024-10, with the labels that each got.

#2485 Use Popover for search window
  libcore/Interfaces/SearchableInterface.vala
  libcore/Widgets/BasicBreadcrumbsEntry.vala
  src/View/Widgets/BreadcrumbsEntry.vala
  src/View/Widgets/LocationBar.vala
  src/View/Widgets/SearchResults.vala
Labels: Gtk4 Preparation

#2408 AbstractDirectoryView: Use EventControllerScroll
  src/View/AbstractDirectoryView.vala
Labels: Gtk4 Preparation

#2504 Fix crash on opening folders just pasted into empty folder.
  data/files.metainfo.xml.in.in
  libcore/ListModel.vala
  src/View/AbstractDirectoryView.vala
Labels: Priority: Critical

#2511 Release 7.1.0
  data/files.metainfo.xml.in.in
  meson.build
Labels: Release
